# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  check:
    name: Assumption check
    runs-on: ubuntu-latest
    steps:
      - name: print base_ref
        run: echo ${{ github.event.base_ref }}
      - name: print merged state
        run: echo ${{ github.event.pull_request.merged }}
      - uses: actions/checkout@v2
  bump:
    name: Bump tag
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_CHAIN_TOKEN }}
          persist-credentials: false
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          source-url: https://nuget.pkg.github.com/KageKirin/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.TOKEN }}

      - name: Configure git
        run: |
          git config --local user.email "kagekirin+ci@gmail.com"
          git config --local user.name "CI Bot"

      - name: Find tag
        run: |
          git fetch --tags
          git tag -l | tail -n 1

      - name: Find tag (old)
        if: false
        run: |
          git describe --tags --abbrev=1 --always
          git describe --tags --abbrev=0

      - name: Set old tag
        run: dotnet run -f net6.0 -- set dotnet-version.csproj `git tag -l | tail -n 1`

      - name: Bump tag
        run: dotnet run -f net6.0 -- bump --patch

      - name: View new tag
        run: dotnet run -f net6.0 -- get

      - name: Commit tag
        run: |
          git add dotnet-version.csproj
          git commit -m "CI - Bump version"

      - name: Set new git tag
        run: |
          git tag -m "CI" `dotnet run -f net6.0 -- get`

      - name: Push tag
        run: |
          git push --tags --password ${{ secrets.GH_CHAIN_TOKEN }}
          git push --follow-tags --password ${{ secrets.GH_CHAIN_TOKEN }}
