# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  bump:
    name: Bump tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          source-url: https://nuget.pkg.github.com/KageKirin/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.TOKEN }}

      - name: Find tag
        run: git describe --tags --abbrev=0

      - name: Set old tag
        run: dotnet run -f net6.0 -- set dotnet-version.csproj `git describe --tags --abbrev=0`

      - name: Bump tag
        run: dotnet run -f net6.0 -- bump --patch

      - name: View new tag
        run: dotnet run -f net6.0 -- get

      - name: Commit tag
        run: |
          git add dotnet-version.csproj
          git commit -m "CI - Bump version"

      - name: Set new git tag
        run: |
          git tag -m "CI" `dotnet run -f net6.0 -- get`

      - name: Push tag
        run: |
          git push origin --follow-tags
